/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Worldpay.Within.Rpc.Types
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class PaymentResponse : TBase
  {

    public string ServerId { get; set; }

    public string ClientId { get; set; }

    public int? TotalPaid { get; set; }

    public ServiceDeliveryToken ServiceDeliveryToken { get; set; }

    public PaymentResponse() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                ServerId = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                ClientId = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                TotalPaid = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.Struct) {
                ServiceDeliveryToken = new ServiceDeliveryToken();
                ServiceDeliveryToken.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("PaymentResponse");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (ServerId != null) {
          field.Name = "serverId";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(ServerId);
          oprot.WriteFieldEnd();
        }
        if (ClientId != null) {
          field.Name = "clientId";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(ClientId);
          oprot.WriteFieldEnd();
        }
        if (TotalPaid != null) {
          field.Name = "totalPaid";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(TotalPaid.Value);
          oprot.WriteFieldEnd();
        }
        if (ServiceDeliveryToken != null) {
          field.Name = "serviceDeliveryToken";
          field.Type = TType.Struct;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          ServiceDeliveryToken.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("PaymentResponse(");
      bool __first = true;
      if (ServerId != null) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ServerId: ");
        __sb.Append(ServerId);
      }
      if (ClientId != null) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ClientId: ");
        __sb.Append(ClientId);
      }
      if (TotalPaid != null) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TotalPaid: ");
        __sb.Append(TotalPaid);
      }
      if (ServiceDeliveryToken != null) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ServiceDeliveryToken: ");
        __sb.Append(ServiceDeliveryToken== null ? "<null>" : ServiceDeliveryToken.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
